/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: ['**/.*'],
  serverDependenciesToBundle: [
    /^@mdx-js\/esbuild.*/,
    /^@mdx-js\/mdx.*/,
    /^bail.*/,
    /^ccount.*/,
    /^character-entities.*/,
    /^character-reference-invalid.*/,
    /^comma-separated-tokens.*/,
    /^decode-named-character-reference.*/,
    /^env-paths.*/,
    /^estree-util-attach-comments.*/,
    /^estree-util-build-jsx.*/,
    /^estree-util-visit.*/,
    /^estree-walker.*/,
    /^fault.*/,
    /^hast-util-to-estree.*/,
    /^hast-util-whitespace.*/,
    /^is-alphabetical.*/,
    /^is-alphanumerical.*/,
    /^is-decimal.*/,
    /^is-hexadecimal.*/,
    /^is-reference.*/,
    /^longest-streak.*/,
    /^mdast-util-definitions.*/,
    /^mdast-util-from-markdown.*/,
    /^mdast-util-frontmatter.*/,
    /^mdast-util-mdx.*/,
    /^mdast-util-to-hast.*/,
    /^mdast-util-to-markdown.*/,
    /^mdast-util-to-string.*/,
    /^mdx-bundler.*/,
    /^micromark-util-decode-numeric-character-reference.*/,
    /^micromark-util-decode-string.*/,
    /^micromark-util-normalize-identifier.*/,
    /^micromark.*/,
    /^parse-entities.*/,
    /^periscopic.*/,
    /^property-information.*/,
    /^remark.*/,
    /^space-separated-tokens.*/,
    /^stringify-entities.*/,
    /^trough.*/,
    /^unified.*/,
    /^unist-builder.*/,
    /^unist-util-generated.*/,
    /^unist-util-is.*/,
    /^unist-util-position-from-estree.*/,
    /^unist-util-position.*/,
    /^unist-util-stringify-position.*/,
    /^unist-util-visit.*/,
    /^vfile.*/,
    /^zwitch.*/,
  ],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
}
